[package]
name = "plcnext-commons"
version = "0.1.0"
authors = ["Martin Boers <mboers@phoenixcontact.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
cpp = "0.4"

[build-dependencies]
cpp_build = "0.4"